### ISSUE TITLE
Convert this repo into a module

### ISSUE THREAD

**Issue by OmnesPotens** [massif-press/long-rim-data#22]
It would be nice if this repo was maintained as a commonjs module like the [lancer-data](https://github.com/massif-press/lancer-data) repo is. I have made the necessary changes on [my fork](https://github.com/OmnesPotens/long-rim-data), but I also added some github workflow files which may not be desired. 

I also published some packages for the various official player LCPs, I hope thats ok. If not, I can unpublish them!

**Comment by msprijatelj** [comment]
I’d like to understand your expected use case of converting this repo into a commonjs module. I could see that it may make CompCon installation easier (and may free up some player LCP storage?) and improve 3rd party access/installation (eg FoundryVTT). But what do *you* think is “nice” about this feature?

**Comment by git-ival** [comment]
I commented on the PR but I'll respond here as well:

> The idea was that any interested developers could use this as a dependency in potential projects. I can see the lancer-data module is already being used to facilitate other less mechanical game aids. I think making the data more accessible from a developer standpoint is low-effort, low or no-maintenance and I don't think it would reduce ease of packaging as LCP zips.
> 
> For example: [Kuenaimaku's lancer-briefings](https://github.com/Kuenaimaku/lancer-briefings/blob/feature/persons-register/package.json) uses the lancer-data module. I also use lancer-data and the other LCP data modules that I packaged in my fork of [lancer-briefings here](https://github.com/OmnesPotens/lancer-briefings/blob/feature/persons-register/package.json).

I feel the benefits you listed are compelling as well, especially if it aids in VTT support. I find that if you make a thing (the data in this case) accessible to developers then it very much incentivizes a higher quality of development. Overall I guess there isn't an upfront benefit to Massif Press or others who use or maintain this repo currently, but it does open up potential benefits (especially for 3rd party access) with little to no drawbacks.

**Comment by OmnesPotens** [comment]
I commented on the PR but I'll respond here as well:

> The idea was that any interested developers could use this as a dependency in potential projects. I can see the lancer-data module is already being used to facilitate other less mechanical game aids. I think making the data more accessible from a developer standpoint is low-effort, low or no-maintenance and I don't think it would reduce ease of packaging as LCP zips.
> 
> For example: [Kuenaimaku's lancer-briefings](https://github.com/Kuenaimaku/lancer-briefings/blob/feature/persons-register/package.json) uses the lancer-data module. I also use lancer-data and the other LCP data modules that I packaged in my fork of [lancer-briefings here](https://github.com/OmnesPotens/lancer-briefings/blob/feature/persons-register/package.json).

I feel the benefits you listed are compelling as well, especially if it aids in VTT support. I find that if you make a thing (the data in this case) accessible to developers then it very much incentivizes a higher quality of development. Overall I guess there isn't an upfront benefit to Massif Press or others who use or maintain this repo currently, but it does open up potential benefits (especially for 3rd party access) with little to no drawbacks.

**Comment by jarena3** [comment]
Implemented
