### ISSUE TITLE
Caliban Autochoke Tag Not Displayed

### ISSUE THREAD

**Issue by ehildebrand** [massif-press/long-rim-data#9]
Firefox, LCP version 1.0.4, Comp/Con version 2.2.6b

Seen behavior:
The Autochoke profile for the "HHS-075 “Flayer” Shotgun" has a "Knockback 5" tag in the data, but Comp/Con only shows the "Knockback 2" of the Standard profile.

![image](https://user-images.githubusercontent.com/15815322/107775387-7e589080-6d40-11eb-8c30-ea26cddaf177.png)

Expected behavior:
"Knockback 2" is changed to "Knockback 5" when the Autochoke profile is selected.

**Comment by msprijatelj** [comment]
Fixed by #6.
